apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: jo-ns
subjects:
- kind: User
  name: centos #Case Sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #Role or cluster role
  name: pod-reader #Must match name of role or clusrerRole to bind
  apiGroup: rbac.authorization.k8s.io
