apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: Group
  name: manager #Case Sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #Role or cluster role
  name: secret-reader #Must match name of role or clusrerRole to bind
  apiGroup: rbac.authorization.k8s.io
