apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jo-ns
  name: deploy-and-pod-reader
rules:
- apiGroups: [""] # "" Indicates core api group
  resources: ["pods","deployment"]
  verbs: ["update"]
