apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jo-ns
  name: configmap-reader
rules:
- apiGroups: [""] # "" Indicates core api group
  resources: ["configmaps"]
  resourceNames: ["mycfgmap"]
  verbs: ["get", "update"]
