apiVersion: v1
kind: Pod
metadata:
  name: cmap-demo
spec:
  containers:
    - name: cmap-demo-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: game-config
  restartPolicy: Never
