apiVersion: v1
kind: Pod
metadata:
  name: jen-vol-local-demo
  labels:
    app: myapp
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    volumeMounts:
    - name: jenkins-home
      mountPath: /var/jenkins_home
  volumes:
  - name: jenkins-home
    hostPath:
      path: /home/centos/jo/jenkins_home 
      type: Directory      
