apiVersion: v1
kind: Pod
metadata:
  name: sec-contx-demo
spec:
  securityContext:
    runAsUser: 111
    runAsGroup: 222
    fsGroup: 333
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-contx-demo-container
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
     allowPrivilegeEscalation: true
