apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  labels:
    name: secret-test
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: db-user-passw
  containers:
  - name: ssh-test-container
    image: httpd
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume-jo"
