apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: mylabel
              operator: In
              values:
              - nslabel
              - eze-az1
              - eze-az2
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            -  key: mylabel
               operator: In
               values:
               - nslabel
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
