apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: jo-ns
  labels:
    name: rs-label
    type: back-end
    mylabel: nslabel
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: nginx
      namespace: jo-ns
      labels:
        name: rs-label
        type: back-end
        mylabel: nslabel
    spec:
      tolerations:
        - key: "taintdemo"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: demo
          image: yogeshraheja/yogeshk8stest
      nodeSelector:
        mylabel: nslabel

  replicas: 2
  selector:
    matchLabels:
      name: rs-label
      type: back-end
      mylabel: nslabel

